server:
  port: 8080
  servlet:
    contextPath: /myservice

#  error:
##    include-message: always
#    include-binding-errors: always
#    include-exception: false

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/myservice?authSource=admin

  application:
    name: myservice

